version: "3.8"

services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - "5555:5555" # Add this for Prisma Studio
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://soknan:Nan123@postgres:5432/todolist
      BETTER_AUTH_SECRET: 82452fc72d67d1af9cb02044ce97e20e15387d75d985ca8d506071e6966bb6c4
      AUTH_URL: http://172.25.144.1:3000
      ALLOWED_DEV_ORIGIN: 172.25.144.1
  postgres:
    image: postgres:16
    container_name: postgres_db_todolist
    restart: no
    environment:
      POSTGRES_USER: soknan
      POSTGRES_PASSWORD: Nan123
      POSTGRES_DB: todolist
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_todolist:/var/lib/postgresql/data

volumes:
  postgres_todolist: