import type { Metadata } from "next";
import { signOut, auth } from "@/auth";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import LiStyleURL from "@/components/main/LiStyleWithURL";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex bg-white dark:bg-black">
            <div className="bg-yellow-500 dark:bg-yellow-950 h-screen sticky top-0 w-40 py-4 list-none">
              <nav>
                <ul className="space-y-1">
                  {
                    session?.user && (
                      <>
                        <LiStyleURL path="/">Home</LiStyleURL>
                        <LiStyleURL path="/projects">Projects</LiStyleURL>
                        <LiStyleURL path="/tags">Tags</LiStyleURL>
                      </>
                    )
                  }
                  <LiStyleURL path="/settings">Settings</LiStyleURL>
                  {
                    !session?.user && (
                      <LiStyleURL path="/register">Register</LiStyleURL>
                    )
                  }
                  <li className="hover:text-blue-500">
                    {
                      session?.user ? (
                        <button className="py-2 hover:bg-yellow-400 hover:cursor-pointer w-full px-4 text-left" onClick={async () => {
                          "use server"
                          await signOut();
                          }}>
                            Logout
                        </button>) 
                      : (<LiStyleURL path="/signin">Login</LiStyleURL>)
                    }
                  </li>
                </ul>
              </nav>
            </div>
            <div className="p-4 flex-1">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
