import type { Metadata } from "next";
import { signOut, auth } from "@/auth";
import { SignIn } from "@/components/auth/signin-button";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div className="border-r h-screen sticky top-0 w-40 p-4 list-none">
            <nav>
              <ul className="space-y-2">
                <li className="hover:text-blue-500">
                  <Link href="/">Home</Link>
                </li>
                <li className="hover:text-blue-500">
                  <Link href="/projects">Projects</Link>
                </li>
                {
                  !session?.user && (
                    <li className="hover:text-blue-500">
                      <Link href="/register">Register</Link>
                    </li>
                  )
                }
                <li className="hover:text-blue-500">
                  {
                    session?.user ? (
                      <button onClick={async () => {
                        "use server"
                        await signOut();
                        }}>
                          Logout
                      </button>) 
                    : (<SignIn />)
                  }
                </li>
              </ul>
            </nav>
          </div>
          <div className="p-4 flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
